title: Natalya Glaser
logo: /assets/img/logo.jpg
description: Supply Chain Analytics Graduate Student
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

gem "github-pages", group: :jekyll_plugins
